---
cog_bundle_version: 3
name: net
description: "Simple network utilities"
version: "0.1"
docker:
  image: "cogcmd/net"
  tag: "0.1"
commands:
  dig:
    executable: "/bundle/dig.sh"
    description: "DNS lookup utility"
    documentation: "dig [--short] [--trace] [--server server] <target>"
    rules:
      - "when command is net:dig allow"
    options:
      short:
        type: bool
        required: false
      type:
        type: string
        required: false
      server:
        type: string
        required: false
templates:
  dig:
    slack: "```{{#body}}{{{.}}}\n{{/body}}```"
